version: "3.3"

services:
  neofura_http:
    build:
      context: "./neo3fura_http"
      args:
        RT: ${RUNTIME:-test}
    environment:
      RUNTIME: ${RUNTIME:-test}
    ports:
      - "1929:1926"
    networks:
      - network
    restart: always
    container_name: service_http_testnet
    volumes:
      - ./logs:/go/application/Logs/
      - ${TOKENURI_TESTNET_DIR:-./tokenURI/testnet}:/go/application/tokenURI/
    depends_on:
      - redis
      - mongo

  neofura_ws:
    build:
      context: "./neo3fura_ws"
      args:
        RT: ${RUNTIME:-test}
    environment:
      RUNTIME: ${RUNTIME:-test}
    ports:
      - "2028:2026"
    networks:
      - network
    restart: always
    container_name: service_ws_testnet
    volumes:
      - ./logs_ws:/go/application/Logs/
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    networks:
      - network
    restart: always
    ports:
      - "6382:6379"
    container_name: cache_test2

  mongo:
    image: mongo
    restart: always
    container_name: mongo_test2
    networks:
      - network
    ports:
      - "27003:27017"
    expose:
      - "27017"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express_test2
    ports:
      - "8083:8081"
    networks:
      - network
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: change_the_admin
      ME_CONFIG_BASICAUTH_PASSWORD: change_the_password
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:v2.6.1
    container_name: prometheus_test2
    ports:
      - "9093:9090"
    expose:
      - "9093"
    networks:
      - network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/data
    depends_on:
      - neofura_http
      - neofura_ws

  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana_test2
    ports:
      - "3002:3000"
    expose:
      - "3002"
    networks:
      - network
    user: "104"
    depends_on:
      - prometheus

networks:
  network:
